export const DATE_FOMRAT = 'DD/MM/YYYY';

export const CURRENCIES = [
  { value: 'AED', label: 'United Arab Emirates Dirham' },
  { value: 'AFN', label: 'Afghan Afghani' },
  { value: 'ALL', label: 'Albanian Lek' },
  { value: 'AMD', label: 'Armenian Dram' },
  { value: 'ANG', label: 'Netherlands Antillean Guilder' },
  { value: 'AOA', label: 'Angolan Kwanza' },
  { value: 'ARS', label: 'Argentine Peso' },
  { value: 'AUD', label: 'Australian Dollar' },
  { value: 'AWG', label: 'Aruban Florin' },
  { value: 'AZN', label: 'Azerbaijani Manat' },
  { value: 'BAM', label: 'Bosnia-Herzegovina Convertible Mark' },
  { value: 'BBD', label: 'Barbadian Dollar' },
  { value: 'BDT', label: 'Bangladeshi Taka' },
  { value: 'BGN', label: 'Bulgarian Lev' },
  { value: 'BHD', label: 'Bahraini Dinar' },
  { value: 'BIF', label: 'Burundian Franc' },
  { value: 'BMD', label: 'Bermudan Dollar' },
  { value: 'BND', label: 'Brunei Dollar' },
  { value: 'BOB', label: 'Bolivian Boliviano' },
  { value: 'BRL', label: 'Brazilian Real' },
  { value: 'BSD', label: 'Bahamian Dollar' },
  { value: 'BTN', label: 'Bhutanese Ngultrum' },
  { value: 'BWP', label: 'Botswanan Pula' },
  { value: 'BYN', label: 'Belarusian Ruble' },
  { value: 'BZD', label: 'Belize Dollar' },
  { value: 'CAD', label: 'Canadian Dollar' },
  { value: 'CDF', label: 'Congolese Franc' },
  { value: 'CHF', label: 'Swiss Franc' },
  { value: 'CLP', label: 'Chilean Peso' },
  { value: 'CNY', label: 'Chinese Yuan' },
  { value: 'COP', label: 'Colombian Peso' },
  { value: 'CRC', label: 'Costa Rican Colón' },
  { value: 'CUP', label: 'Cuban Peso' },
  { value: 'CVE', label: 'Cape Verdean Escudo' },
  { value: 'CZK', label: 'Czech Republic Koruna' },
  { value: 'DJF', label: 'Djiboutian Franc' },
  { value: 'DKK', label: 'Danish Krone' },
  { value: 'DOP', label: 'Dominican Peso' },
  { value: 'DZD', label: 'Algerian Dinar' },
  { value: 'EGP', label: 'Egyptian Pound' },
  { value: 'ERN', label: 'Eritrean Nakfa' },
  { value: 'ETB', label: 'Ethiopian Birr' },
  { value: 'EUR', label: 'Euro' },
  { value: 'FJD', label: 'Fijian Dollar' },
  { value: 'FKP', label: 'Falkland Islands Pound' },
  { value: 'FOK', label: 'Faroese Króna' },
  { value: 'GBP', label: 'British Pound Sterling' },
  { value: 'GEL', label: 'Georgian Lari' },
  { value: 'GGP', label: 'Guernsey Pound' },
  { value: 'GHS', label: 'Ghanaian Cedi' },
  { value: 'GIP', label: 'Gibraltar Pound' },
  { value: 'GMD', label: 'Gambian Dalasi' },
  { value: 'GNF', label: 'Guinean Franc' },
  { value: 'GTQ', label: 'Guatemalan Quetzal' },
  { value: 'GYD', label: 'Guyanaese Dollar' },
  { value: 'HKD', label: 'Hong Kong Dollar' },
  { value: 'HNL', label: 'Honduran Lempira' },
  { value: 'HRK', label: 'Croatian Kuna' },
  { value: 'HTG', label: 'Haitian Gourde' },
  { value: 'HUF', label: 'Hungarian Forint' },
  { value: 'IDR', label: 'Indonesian Rupiah' },
  { value: 'ILS', label: 'Israeli New Sheqel' },
  { value: 'IMP', label: 'Manx Pound' },
  { value: 'INR', label: 'Indian Rupee' },
  { value: 'IQD', label: 'Iraqi Dinar' },
  { value: 'IRR', label: 'Iranian Rial' },
  { value: 'ISK', label: 'Icelandic Króna' },
  { value: 'JEP', label: 'Jersey Pound' },
  { value: 'JMD', label: 'Jamaican Dollar' },
  { value: 'JOD', label: 'Jordanian Dinar' },
  { value: 'JPY', label: 'Japanese Yen' },
  { value: 'KES', label: 'Kenyan Shilling' },
  { value: 'KGS', label: 'Kyrgyzstani Som' },
  { value: 'KHR', label: 'Cambodian Riel' },
  { value: 'KID', label: 'Kiribati Dollar' },
  { value: 'KMF', label: 'Comorian Franc' },
  { value: 'KRW', label: 'South Korean Won' },
  { value: 'KWD', label: 'Kuwaiti Dinar' },
  { value: 'KYD', label: 'Cayman Islands Dollar' },
  { value: 'KZT', label: 'Kazakhstani Tenge' },
  { value: 'LAK', label: 'Laotian Kip' },
  { value: 'LBP', label: 'Lebanese Pound' },
  { value: 'LKR', label: 'Sri Lankan Rupee' },
  { value: 'LRD', label: 'Liberian Dollar' },
  { value: 'LSL', label: 'Lesotho Loti' },
  { value: 'LYD', label: 'Libyan Dinar' },
  { value: 'MAD', label: 'Moroccan Dirham' },
  { value: 'MDL', label: 'Moldovan Leu' },
  { value: 'MGA', label: 'Malagasy Ariary' },
  { value: 'MKD', label: 'Macedonian Denar' },
  { value: 'MMK', label: 'Myanma Kyat' },
  { value: 'MNT', label: 'Mongolian Tugrik' },
  { value: 'MOP', label: 'Macanese Pataca' },
  { value: 'MRU', label: 'Mauritanian Ouguiya' },
  { value: 'MUR', label: 'Mauritian Rupee' },
  { value: 'MVR', label: 'Maldivian Rufiyaa' },
  { value: 'MWK', label: 'Malawian Kwacha' },
  { value: 'MXN', label: 'Mexican Peso' },
  { value: 'MYR', label: 'Malaysian Ringgit' },
  { value: 'MZN', label: 'Mozambican Metical' },
  { value: 'NAD', label: 'Namibian Dollar' },
  { value: 'NGN', label: 'Nigerian Naira' },
  { value: 'NIO', label: 'Nicaraguan Córdoba' },
  { value: 'NOK', label: 'Norwegian Krone' },
  { value: 'NPR', label: 'Nepalese Rupee' },
  { value: 'NZD', label: 'New Zealand Dollar' },
  { value: 'OMR', label: 'Omani Rial' },
  { value: 'PAB', label: 'Panamanian Balboa' },
  { value: 'PEN', label: 'Peruvian Nuevo Sol' },
  { value: 'PGK', label: 'Papua New Guinean Kina' },
  { value: 'PHP', label: 'Philippine Peso' },
  { value: 'PKR', label: 'Pakistani Rupee' },
  { value: 'PLN', label: 'Polish Złoty' },
  { value: 'PYG', label: 'Paraguayan Guaraní' },
  { value: 'QAR', label: 'Qatari Rial' },
  { value: 'RON', label: 'Romanian Leu' },
  { value: 'RSD', label: 'Serbian Dinar' },
  { value: 'RUB', label: 'Russian Ruble' },
  { value: 'RWF', label: 'Rwandan Franc' },
  { value: 'SAR', label: 'Saudi Riyal' },
  { value: 'SBD', label: 'Solomon Islands Dollar' },
  { value: 'SCR', label: 'Seychellois Rupee' },
  { value: 'SDG', label: 'Sudanese Pound' },
  { value: 'SEK', label: 'Swedish Krona' },
  { value: 'SGD', label: 'Singapore Dollar' },
  { value: 'SHP', label: 'Saint Helena Pound' },
  { value: 'SLL', label: 'Sierra Leonean Leone' },
  { value: 'SOS', label: 'Somali Shilling' },
  { value: 'SRD', label: 'Surinamese Dollar' },
  { value: 'SSP', label: 'South Sudanese Pound' },
  { value: 'STN', label: 'São Tomé and Príncipe Dobra' },
  { value: 'SYP', label: 'Syrian Pound' },
  { value: 'SZL', label: 'Swazi Lilangeni' },
  { value: 'THB', label: 'Thai Baht' },
  { value: 'TJS', label: 'Tajikistani Somoni' },
  { value: 'TMT', label: 'Turkmenistani Manat' },
  { value: 'TND', label: 'Tunisian Dinar' },
  { value: 'TOP', label: 'Tongan Paʻanga' },
  { value: 'TRY', label: 'Turkish Lira' },
  { value: 'TTD', label: 'Trinidad and Tobago Dollar' },
  { value: 'TVD', label: 'Tuvaluan Dollar' },
  { value: 'TWD', label: 'New Taiwan Dollar' },
  { value: 'TZS', label: 'Tanzanian Shilling' },
  { value: 'UAH', label: 'Ukrainian Hryvnia' },
  { value: 'UGX', label: 'Ugandan Shilling' },
  { value: 'USD', label: 'United States Dollar' },
  { value: 'UYU', label: 'Uruguayan Peso' },
  { value: 'UZS', label: 'Uzbekistan Som' },
  { value: 'VES', label: 'Venezuelan Bolívar Soberano' },
  { value: 'VND', label: 'Vietnamese Dong' },
  { value: 'VUV', label: 'Vanuatu Vatu' },
  { value: 'WST', label: 'Samoan Tala' },
  { value: 'XAF', label: 'CFA Franc BEAC' },
  { value: 'XCD', label: 'East Caribbean Dollar' },
  { value: 'XDR', label: 'Special Drawing Rights' },
  { value: 'XOF', label: 'CFA Franc BCEAO' },
  { value: 'XPF', label: 'CFP Franc' },
  { value: 'YER', label: 'Yemeni Rial' },
  { value: 'ZAR', label: 'South African Rand' },
  { value: 'ZMW', label: 'Zambian Kwacha' },
  { value: 'ZWL', label: 'Zimbabwean Dollar' },
];

export const COUNTRIES = [
  { value: 'AF', label: 'Afghanistan' },
  { value: 'AX', label: 'Åland Islands' },
  { value: 'AL', label: 'Albania' },
  { value: 'DZ', label: 'Algeria' },
  { value: 'AS', label: 'American Samoa' },
  { value: 'AD', label: 'Andorra' },
  { value: 'AO', label: 'Angola' },
  { value: 'AI', label: 'Anguilla' },
  { value: 'AQ', label: 'Antarctica' },
  { value: 'AG', label: 'Antigua and Barbuda' },
  { value: 'AR', label: 'Argentina' },
  { value: 'AM', label: 'Armenia' },
  { value: 'AW', label: 'Aruba' },
  { value: 'AU', label: 'Australia' },
  { value: 'AT', label: 'Austria' },
  { value: 'AZ', label: 'Azerbaijan' },
  { value: 'BS', label: 'Bahamas' },
  { value: 'BH', label: 'Bahrain' },
  { value: 'BD', label: 'Bangladesh' },
  { value: 'BB', label: 'Barbados' },
  { value: 'BY', label: 'Belarus' },
  { value: 'BE', label: 'Belgium' },
  { value: 'BZ', label: 'Belize' },
  { value: 'BJ', label: 'Benin' },
  { value: 'BM', label: 'Bermuda' },
  { value: 'BT', label: 'Bhutan' },
  { value: 'BO', label: 'Bolivia (Plurinational State of)' },
  { value: 'BQ', label: 'Bonaire, Sint Eustatius and Saba' },
  { value: 'BA', label: 'Bosnia and Herzegovina' },
  { value: 'BW', label: 'Botswana' },
  { value: 'BV', label: 'Bouvet Island' },
  { value: 'BR', label: 'Brazil' },
  { value: 'IO', label: 'British Indian Ocean Territory' },
  { value: 'BN', label: 'Brunei Darussalam' },
  { value: 'BG', label: 'Bulgaria' },
  { value: 'BF', label: 'Burkina Faso' },
  { value: 'BI', label: 'Burundi' },
  { value: 'CV', label: 'Cabo Verde' },
  { value: 'KH', label: 'Cambodia' },
  { value: 'CM', label: 'Cameroon' },
  { value: 'CA', label: 'Canada' },
  { value: 'KY', label: 'Cayman Islands' },
  { value: 'CF', label: 'Central African Republic' },
  { value: 'TD', label: 'Chad' },
  { value: 'CL', label: 'Chile' },
  { value: 'CN', label: 'China' },
  { value: 'CX', label: 'Christmas Island' },
  { value: 'CC', label: 'Cocos (Keeling) Islands' },
  { value: 'CO', label: 'Colombia' },
  { value: 'KM', label: 'Comoros' },
  { value: 'CG', label: 'Congo' },
  { value: 'CD', label: 'Congo, Democratic Republic of the' },
  { value: 'CK', label: 'Cook Islands' },
  { value: 'CR', label: 'Costa Rica' },
  { value: 'CI', label: "Côte d'Ivoire" },
  { value: 'HR', label: 'Croatia' },
  { value: 'CU', label: 'Cuba' },
  { value: 'CW', label: 'Curaçao' },
  { value: 'CY', label: 'Cyprus' },
  { value: 'CZ', label: 'Czechia' },
  { value: 'DK', label: 'Denmark' },
  { value: 'DJ', label: 'Djibouti' },
  { value: 'DM', label: 'Dominica' },
  { value: 'DO', label: 'Dominican Republic' },
  { value: 'EC', label: 'Ecuador' },
  { value: 'EG', label: 'Egypt' },
  { value: 'SV', label: 'El Salvador' },
  { value: 'GQ', label: 'Equatorial Guinea' },
  { value: 'ER', label: 'Eritrea' },
  { value: 'EE', label: 'Estonia' },
  { value: 'ET', label: 'Ethiopia' },
  { value: 'FK', label: 'Falkland Islands (Malvinas)' },
  { value: 'FO', label: 'Faroe Islands' },
  { value: 'FJ', label: 'Fiji' },
  { value: 'FI', label: 'Finland' },
  { value: 'FR', label: 'France' },
  { value: 'GF', label: 'French Guiana' },
  { value: 'PF', label: 'French Polynesia' },
  { value: 'TF', label: 'French Southern Territories' },
  { value: 'GA', label: 'Gabon' },
  { value: 'GM', label: 'Gambia' },
  { value: 'GE', label: 'Georgia' },
  { value: 'DE', label: 'Germany' },
  { value: 'GH', label: 'Ghana' },
  { value: 'GI', label: 'Gibraltar' },
  { value: 'GR', label: 'Greece' },
  { value: 'GL', label: 'Greenland' },
  { value: 'GD', label: 'Grenada' },
  { value: 'GP', label: 'Guadeloupe' },
  { value: 'GU', label: 'Guam' },
  { value: 'GT', label: 'Guatemala' },
  { value: 'GG', label: 'Guernsey' },
  { value: 'GN', label: 'Guinea' },
  { value: 'GW', label: 'Guinea-Bissau' },
  { value: 'GY', label: 'Guyana' },
  { value: 'HT', label: 'Haiti' },
  { value: 'HM', label: 'Heard Island and McDonald Islands' },
  { value: 'VA', label: 'Holy See' },
  { value: 'HN', label: 'Honduras' },
  { value: 'HK', label: 'Hong Kong' },
  { value: 'HU', label: 'Hungary' },
  { value: 'IS', label: 'Iceland' },
  { value: 'IN', label: 'India' },
  { value: 'ID', label: 'Indonesia' },
  { value: 'IR', label: 'Iran' },
  { value: 'IQ', label: 'Iraq' },
  { value: 'IE', label: 'Ireland' },
  { value: 'IM', label: 'Isle of Man' },
  { value: 'IT', label: 'Italy' },
  { value: 'JM', label: 'Jamaica' },
  { value: 'JP', label: 'Japan' },
  { value: 'JE', label: 'Jersey' },
  { value: 'JO', label: 'Jordan' },
  { value: 'KZ', label: 'Kazakhstan' },
  { value: 'KE', label: 'Kenya' },
  { value: 'KI', label: 'Kiribati' },
  { value: 'KP', label: "Korea (Democratic People's Republic of)" },
  { value: 'KR', label: 'Korea (Republic of)' },
  { value: 'KW', label: 'Kuwait' },
  { value: 'KG', label: 'Kyrgyzstan' },
  { value: 'LA', label: "Lao People's Democratic Republic" },
  { value: 'LV', label: 'Latvia' },
  { value: 'LB', label: 'Lebanon' },
  { value: 'LS', label: 'Lesotho' },
  { value: 'LR', label: 'Liberia' },
  { value: 'LY', label: 'Libya' },
  { value: 'LI', label: 'Liechtenstein' },
  { value: 'LT', label: 'Lithuania' },
  { value: 'LU', label: 'Luxembourg' },
  { value: 'MO', label: 'Macao' },
  { value: 'MG', label: 'Madagascar' },
  { value: 'MW', label: 'Malawi' },
  { value: 'MY', label: 'Malaysia' },
  { value: 'MV', label: 'Maldives' },
  { value: 'ML', label: 'Mali' },
  { value: 'MT', label: 'Malta' },
  { value: 'MH', label: 'Marshall Islands' },
  { value: 'MQ', label: 'Martinique' },
  { value: 'MR', label: 'Mauritania' },
  { value: 'MU', label: 'Mauritius' },
  { value: 'YT', label: 'Mayotte' },
  { value: 'MX', label: 'Mexico' },
  { value: 'FM', label: 'Micronesia (Federated States of)' },
  { value: 'MD', label: 'Moldova (Republic of)' },
  { value: 'MC', label: 'Monaco' },
  { value: 'MN', label: 'Mongolia' },
  { value: 'ME', label: 'Montenegro' },
  { value: 'MS', label: 'Montserrat' },
  { value: 'MA', label: 'Morocco' },
  { value: 'MZ', label: 'Mozambique' },
  { value: 'MM', label: 'Myanmar' },
  { value: 'NA', label: 'Namibia' },
  { value: 'NR', label: 'Nauru' },
  { value: 'NP', label: 'Nepal' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'NC', label: 'New Caledonia' },
  { value: 'NZ', label: 'New Zealand' },
  { value: 'NI', label: 'Nicaragua' },
  { value: 'NE', label: 'Niger' },
  { value: 'NG', label: 'Nigeria' },
  { value: 'NU', label: 'Niue' },
  { value: 'NF', label: 'Norfolk Island' },
  { value: 'MP', label: 'Northern Mariana Islands' },
  { value: 'NO', label: 'Norway' },
  { value: 'OM', label: 'Oman' },
  { value: 'PK', label: 'Pakistan' },
  { value: 'PW', label: 'Palau' },
  { value: 'PS', label: 'Palestine' },
  { value: 'PA', label: 'Panama' },
  { value: 'PG', label: 'Papua New Guinea' },
  { value: 'PY', label: 'Paraguay' },
  { value: 'PE', label: 'Peru' },
  { value: 'PH', label: 'Philippines' },
  { value: 'PN', label: 'Pitcairn' },
  { value: 'PL', label: 'Poland' },
  { value: 'PT', label: 'Portugal' },
  { value: 'PR', label: 'Puerto Rico' },
  { value: 'QA', label: 'Qatar' },
  { value: 'RE', label: 'Réunion' },
  { value: 'RO', label: 'Romania' },
  { value: 'RU', label: 'Russian Federation' },
  { value: 'RW', label: 'Rwanda' },
  { value: 'BL', label: 'Saint Barthélemy' },
  { value: 'SH', label: 'Saint Helena, Ascension and Tristan da Cunha' },
  { value: 'KN', label: 'Saint Kitts and Nevis' },
  { value: 'LC', label: 'Saint Lucia' },
  { value: 'MF', label: 'Saint Martin (French part)' },
  { value: 'PM', label: 'Saint Pierre and Miquelon' },
  { value: 'VC', label: 'Saint Vincent and the Grenadines' },
  { value: 'WS', label: 'Samoa' },
  { value: 'SM', label: 'San Marino' },
  { value: 'ST', label: 'Sao Tome and Principe' },
  { value: 'SA', label: 'Saudi Arabia' },
  { value: 'SN', label: 'Senegal' },
  { value: 'RS', label: 'Serbia' },
  { value: 'SC', label: 'Seychelles' },
  { value: 'SL', label: 'Sierra Leone' },
  { value: 'SG', label: 'Singapore' },
  { value: 'SX', label: 'Sint Maarten (Dutch part)' },
  { value: 'SK', label: 'Slovakia' },
  { value: 'SI', label: 'Slovenia' },
  { value: 'SB', label: 'Solomon Islands' },
  { value: 'SO', label: 'Somalia' },
  { value: 'ZA', label: 'South Africa' },
  { value: 'GS', label: 'South Georgia and the South Sandwich Islands' },
  { value: 'SS', label: 'South Sudan' },
  { value: 'ES', label: 'Spain' },
  { value: 'LK', label: 'Sri Lanka' },
  { value: 'SD', label: 'Sudan' },
  { value: 'SR', label: 'Suriname' },
  { value: 'SJ', label: 'Svalbard and Jan Mayen' },
  { value: 'SE', label: 'Sweden' },
  { value: 'CH', label: 'Switzerland' },
  { value: 'SY', label: 'Syrian Arab Republic' },
  { value: 'TW', label: 'Taiwan' },
  { value: 'TJ', label: 'Tajikistan' },
  { value: 'TZ', label: 'Tanzania, United Republic of' },
  { value: 'TH', label: 'Thailand' },
  { value: 'TL', label: 'Timor-Leste' },
  { value: 'TG', label: 'Togo' },
  { value: 'TK', label: 'Tokelau' },
  { value: 'TO', label: 'Tonga' },
  { value: 'TT', label: 'Trinidad and Tobago' },
  { value: 'TN', label: 'Tunisia' },
  { value: 'TR', label: 'Turkey' },
  { value: 'TM', label: 'Turkmenistan' },
  { value: 'TC', label: 'Turks and Caicos Islands' },
  { value: 'TV', label: 'Tuvalu' },
  { value: 'UG', label: 'Uganda' },
  { value: 'UA', label: 'Ukraine' },
  { value: 'AE', label: 'United Arab Emirates' },
  {
    value: 'GB',
    label: 'United Kingdom of Great Britain and Northern Ireland',
  },
  { value: 'US', label: 'United States of America' },
  { value: 'UM', label: 'United States Minor Outlying Islands' },
  { value: 'UY', label: 'Uruguay' },
  { value: 'UZ', label: 'Uzbekistan' },
  { value: 'VU', label: 'Vanuatu' },
  { value: 'VE', label: 'Venezuela (Bolivarian Republic of)' },
  { value: 'VN', label: 'Viet Nam' },
  { value: 'VG', label: 'Virgin Islands (British)' },
  { value: 'VI', label: 'Virgin Islands (U.S.)' },
  { value: 'WF', label: 'Wallis and Futuna' },
  { value: 'EH', label: 'Western Sahara' },
  { value: 'YE', label: 'Yemen' },
  { value: 'ZM', label: 'Zambia' },
  { value: 'ZW', label: 'Zimbabwe' },
];

export const TERM_OF_PAYMENT = [
  { label: '1/2% 10 NET 30', value: 'half-10-net-30' },
  { label: '1/2% 10 NET 45', value: 'half-10-net-45' },
  { label: '1/2% 10 NET 60', value: 'half-10-net-60' },
  { label: 'CASH B4 DELIVERY', value: 'cash-b4-delivery' },
  { label: 'CASH ON DELIVERY', value: 'cash-on-delivery' },
  { label: 'NET 10', value: 'net-10' },
  { label: 'NET 15', value: 'net-15' },
  { label: 'NET 30', value: 'net-30' },
  { label: 'NET 30, 1% 10 DAYS', value: 'net-30-1pct-10-days' },
  { label: 'NET 30, 1/2% 10 DAYS', value: 'net-30-half-10-days' },
  { label: 'NET 45', value: 'net-45' },
  { label: 'NET 60', value: 'net-60' },
];

export const TRANSACTION_TYPES = [
  { label: 'Invoice', value: 'INVOICE' },
  { label: 'Credit Note', value: 'CREDIT_NOTE' },
  { label: 'Debit Note', value: 'DEBIT_NOTE' },
  { label: 'Payment', value: 'PAYMENT' },
  { label: 'Advance Payment', value: 'ADVANCE_PAYMENT' },
  { label: 'Refund', value: 'REFUND' },
  { label: 'Write-off', value: 'WRITE_OFF' },
  { label: 'Adjustment', value: 'ADJUSTMENT' },
  { label: 'Reversal', value: 'REVERSAL' },
  { label: 'Recurring Invoice', value: 'RECURRING_INVOICE' },
];

export const DOCUMENT_TYPES = [
  { label: 'Sales Invoice', value: 'SALES_INVOICE' },
  { label: 'Proforma Invoice', value: 'PROFORMA_INVOICE' },
  { label: 'Commercial Invoice', value: 'COMMERCIAL_INVOICE' },
  { label: 'Credit Memo', value: 'CREDIT_MEMO' },
  { label: 'Debit Memo', value: 'DEBIT_MEMO' },
  { label: 'Payment Receipt', value: 'PAYMENT_RECEIPT' },
  { label: 'Tax Invoice', value: 'TAX_INVOICE' },
  { label: 'Purchase Invoice', value: 'PURCHASE_INVOICE' },
  { label: 'Time Invoice', value: 'TIME_INVOICE' },
  { label: 'Recurring Invoice Document', value: 'RECURRING_INVOICE_DOCUMENT' },
];


export const INVOICE_ITEMS_HEADER = [
  'Line Item Number',
  'Account',
  'Amount',
  'Department',
  'Quantity',
  'Description',
];

export const INVOICE_FIELD_OPTIONS = [
  { label: "Supplier Name", value: "supplierName" },
  { label: "PO Number", value: "poNumber" },
  { label: "Invoice Number", value: "invoiceNumber" },
  { label: "Invoice Date", value: "invoiceDate" },
  { label: "Currency", value: "currency" },
  { label: "Vendor ID", value: "vendorId" },
  { label: "VAT Number", value: "vatNumber" },
  { label: "Payment Terms", value: "paymentTerms" },
  { label: "Payment Term Description", value: "paymentTermDescription" },
  { label: "Rarity Invoice", value: "rarityInvoice" },
  { label: "Amount", value: "amount" },
  { label: "Amount Without VAT", value: "amountWithoutVat" },
  { label: "VAT Percentage", value: "vatPercentage" },
  { label: "Terms of Payment", value: "termsOfPayment" },
  { label: "File URL", value: "fileUrl" },
  { label: "Comment", value: "comment" },
  { label: "Matched With PO", value: "matchedWithPO" },
  { label: "Is Duplicate", value: "isDuplicate" },
  { label: "File Name", value: "fileName" },
  { label: "JCI Number", value: "jciNumber" },
  { label: "Location", value: "location" },
  { label: "Internal Partner Code", value: "internalPartnerCode" },
  { label: "Country Code", value: "countryCode" },
  { label: "Is Local Invoice", value: "isLocalInvoice" },
  { label: "Transaction Type", value: "transactionType" },
  { label: "Document Type", value: "documentType" },
];

export const INVOICE_ITEM_MAPPING_OPTIONS = [
  { label: "GL Account", value: "glAccount" },
  { label: "Amount", value: "amount" },
  { label: "Description", value: "description" },
  { label: "Department", value: "department" },
  { label: "Quantity", value: "quantity" },
  { label: "Line Item Number", value: "lineItemNumber" },
];