export const ROUTES = {
  auth: '/auth',
  login: 'login',
  signup: 'signup',
  documents: '/documents',
  messages: '/messages',
  invoices: '/invoices',
  customer_review: '/customer-review',
  suppliers: '/suppliers',
  payment: '/payment',
  approval: '/approval',
  posting: '/posting',
  reports: '/reports',
  team: '/team',
  settings: '/settings',
  not_available: '/not-available',
  profile: 'profile',
  forgotPassword: 'forgot-password',
  reset: "reset-password",
  export_configuration: 'export-configuration',
  import_dataset: "import-dataset",
  export_invoice: "export-invoice"
};
